flaskr/demo/__init__.py
from flask import Blueprint

app = Blueprint('demo',
    __name__,
    template_folder='templates',
    static_folder='static')

from . import views

flaskr/demo/views.py
from flask import render_template, request
from . import app


@app.route('/')
def home():
    return render_template("home.html")


@app.route('/fixjq')
def fixjq():
    return render_template("fixing_jq.html")

@app.route('/reflect')
def reflect():
    param = request.args.get('p', '')
    return render_template("reflect.html", param=param)


@app.route('/badreflect')
def badreflect():
    param = request.args.get('p', '')
    return render_template("badreflect.html", param=param)


@app.route('/domxss1')
def domxss1():
    return render_template("hashreflect.html")


@app.route('/otherheaders')
def otherheaders():
    return render_template("otherheaders.html", request=request)


@app.route('/demoangular')
def demoangular():
    return render_template("demoangular.html")

flaskr/demo/templates/badreflect.html
{% extends "base.html" %}
{% block content %}
<form class="form-inline" action='{{url_for('demo.badreflect')}}' method='GET'>
  <input id='param' class="form-control mr-sm-2" type="text" name="p" placeholder="parameter">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

<p><div id="reflect">{{ param }}</div></p>
<button class="btn btn-outline-success my-2 my-sm-0" onclick="copypasta()">Copy pasta</button>
<p><div id="inject"></div></p>
<a href="{{url_for('demo.fixjq')}}" class="btn btn-outline-info my-2 my-sm-0" onclick="copypasta()">How 2 fix it</a>
{% endblock content %}


{% block javascript %}
<script>
// don't hurt me. Jquery is easier to write
var copypasta = () => {
  let output = $("#reflect").text();
  console.log(output);
  $('#inject').html(output);
};
</script>
{% endblock javascript %}

flaskr/demo/templates/demoangular.html
{% extends "base.html" %}
{% block content %}
{% raw %}
<div ng-app="myApp" ng-controller="myCtrl">
  <p>fill me in: <input ng-model="firstname"></p>
  <h1>{{firstname}}</h1>

  <p>More demo of angular stuff: {{ 5 * 5 }}</p>
  <p>Unfortunately some things don't work {{ document.location }}</p>
  <p>Like this: {{ alert(1) }}</p>
</div>
{% endraw %}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
<script>
var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope) {
    $scope.firstname = ":norman:";
});
</script>
{% endblock content %}

flaskr/demo/templates/fixing_jq.html
{% extends "base.html" %}
{% block content %}
<h3>Original Javascript</h3>
<figure class="highlight">
<pre><code>
// don't hurt me. Jquery is easier to write
var copypasta = () => {
  let output = $("#reflect").text();
  console.log(output);
  $('#inject').html(output);
};
</code></pre>
</figure>

<h3>Better Code</h3>
<figure class="highlight">
<pre><code>
// don't hurt me. Jquery is easier to write
var copypasta = () => {
  let output = $("#reflect").html();
  console.log(output);
  $('#inject').html(output);
};
</code></pre>
</figure>
<p>jQuery y u do dis</p>
<p><a href="https://stackoverflow.com/questions/4459992/differences-between-text-and-html-with-escaped-and-characters">Stack Overflow Sauce</a></p>
<p>This is in accordance with the corresponding JavaScript methods textContent and innerHTML.</p>

<figure class="highlight">
<pre><code>
>> console.log(document.getElementsByTagName('p')[0].textContent);
hello &lt;world&gt;

>> console.log(document.getElementsByTagName('p')[0].innerHTML);
hello &amp;lt;world&amp;gt;
<!-- if you're viewing source. This is double escaped to show the example better in live HTML --!>
</code></pre>
</figure>


{% endblock content %}

flaskr/demo/templates/hashreflect.html
{% extends "base.html" %}
{% block content %}
<form class="form-inline" action='{{url_for('demo.reflect')}}' method='GET'>
  <input id='param' class="form-control mr-sm-2" type="text" name="p" placeholder="parameter">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

<p><span id="inject"></span></p>
{% endblock content %}


{% block javascript %}
<script>
// don't hurt me. Jquery is easier to write
$(document).ready(() => {
  console.log("Hello. This is the DOM Based XSS challenge. ");
  let update = () => $('#inject').html(document.location.hash);
  update();
  $('form').submit((e) => {
    e.preventDefault();
    document.location.hash = $('input[name=p]').val();
    update();
  })
})
</script>
{% endblock %}

flaskr/demo/templates/home.html
{% extends "base.html" %}
{% block content %}
I hope you're ready for some learning
{% endblock content %}

flaskr/demo/templates/otherheaders.html
{% extends "base.html" %}
{% block content %}
{% autoescape false %}
{% for k,v in request.headers.items() %}
  <p><b>{{ k }}:</b> {{ v }}</p>
{% endfor %}
{% endautoescape %}
{% endblock content %}

flaskr/demo/templates/reflect.html
{% extends "base.html" %}
{% block content %}
<form class="form-inline" action='{{url_for('demo.reflect')}}' method='GET'>
  <input class="form-control mr-sm-2" type="text" name="p" placeholder="parameter">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
{% autoescape false %}
{{ param }}
{% endautoescape %}
{% endblock content %}