flaskr/base_xss/models.py
from ..main import db

class Xss(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.UnicodeText(500), index=True)
    content = db.Column(db.UnicodeText(500), index=True)

flaskr/models.py
from .main import db
from .base_xss import models
from .normal_xss import models

flaskr/normal_xss/models.py
from ..main import db

class Xss2(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.UnicodeText(500), index=True)
    content = db.Column(db.UnicodeText(500), index=True)

flaskr/__init__.py
from .main import app

flaskr/base_xss/__init__.py
from flask import Blueprint

base_xss = Blueprint('base_xss',
    __name__,
    template_folder='templates',
    static_folder='static')

from . import views

flaskr/base_xss/views.py
from flask import render_template, request, render_template_string, redirect, current_app
from multiprocessing import Process
from ..main import db
from . import base_xss
from . import phantom
from .models import Xss
flag1 = 'lectureCTF{wasnt-that-hard-was-it}'

@base_xss.route('/f4b79862d3dbfcc2c45ae07df16d0d6f')
def xss_set_flag_cookie():
    redirect_to_index = redirect('/')
    response = current_app.make_response(redirect_to_index)
    response.set_cookie('totally_not_the_flag', value=flag1)
    return response


@base_xss.route('/<xss_id>')
def xss_post_page(xss_id):
    if xss_id == '404':
        return render_template_string('')

    xss = Xss.query.filter_by(id=xss_id).scalar()
    if xss is None:
        return render_template_string("404")
    print('[+] XSS Payload Request: ID: ', xss_id, xss.content, '|', xss.id,
          '|', xss.title)
    return render_template('post.html', xss=xss)


@base_xss.route('/', methods=['GET', 'POST'])
@base_xss.route('/create', methods=['GET', 'POST'])
def xss_create_page():
    if request.method == 'GET':
        message = 'hello'
        return render_template('create.html', message=message)
    elif request.method == 'POST':
        title = request.form.get('title', '')
        content = request.form.get('content', '')
        # process payload here if you want to do anything with it
        title = xss_filter(title)
        content = xss_filter(content)
        new_xss = Xss(title=title, content=content)
        db.session.add(new_xss)
        db.session.commit()
        if "PhantomJS" not in request.headers['User-Agent']:
            print("Calling phantomJS")
            p = Process(
                target=phantom.xss_get,
                args=(request.url_root + str(new_xss.id), ))
            p.start()
        return render_template(
            'success.html', id=new_xss.id, title=title, content=content)


def xss_filter(payload):
    payload = payload.replace("script", "XSS ATTEMPT DETECTED")
    payload = payload.replace('<', '&lt;')
    payload = payload.replace('>', '&gt;')
    return payload

flaskr/demo/__init__.py
from flask import Blueprint

app = Blueprint('demo',
    __name__,
    template_folder='templates',
    static_folder='static')

from . import views

flaskr/demo/views.py
from flask import render_template, request
from . import app


@app.route('/')
def home():
    return render_template("home.html")


@app.route('/fixjq')
def fixjq():
    return render_template("fixing_jq.html")

@app.route('/reflect')
def reflect():
    param = request.args.get('p', '')
    return render_template("reflect.html", param=param)


@app.route('/badreflect')
def badreflect():
    param = request.args.get('p', '')
    return render_template("badreflect.html", param=param)


@app.route('/domxss1')
def domxss1():
    return render_template("hashreflect.html")


@app.route('/otherheaders')
def otherheaders():
    return render_template("otherheaders.html", request=request)


@app.route('/demoangular')
def demoangular():
    return render_template("demoangular.html")

flaskr/main.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_user import UserManager, SQLAlchemyAdapter

class ConfigClass(object):
    # Flask settings
    SECRET_KEY                      = 'idgafabotusecuresecretshahahahah'
    SQLALCHEMY_DATABASE_URI         = 'sqlite:///basic_app.sqlite'
    SQLALCHEMY_ECHO                 = True
    USER_ENABLE_EMAIL               = False
    USER_ENABLE_CONFIRM_EMAIL       = False
    USER_ENABLE_FORGOT_PASSWORD     = False
    USER_ENABLE_LOGIN_WITHOUT_CONFIRM = True
    USER_AUTO_LOGIN                  = True
    USER_AUTO_LOGIN_AFTER_CONFIRM    = USER_AUTO_LOGIN
    USER_AUTO_LOGIN_AFTER_REGISTER   = USER_AUTO_LOGIN
    USER_AUTO_LOGIN_AFTER_RESET_PASSWORD = USER_AUTO_LOGIN
    USER_PASSWORD_HASH_MODE = 'plaintext'

db = SQLAlchemy()

app = Flask(__name__)
app.config.from_object(__name__+'.ConfigClass')

db.init_app(app)

from . import models
with app.app_context():
    db.create_all()

from .base_xss import base_xss
from .normal_xss import app as normal_xss
from .demo import app as demo_blueprint
app.register_blueprint(demo_blueprint)
app.register_blueprint(base_xss, url_prefix="/xss")
app.register_blueprint(normal_xss, url_prefix="/xss2")

flaskr/normal_xss/__init__.py
from flask import Blueprint

app = Blueprint('normal_xss',
    __name__,
    template_folder='templates',
    static_folder='static')

from . import views

flaskr/normal_xss/views.py
from flask import render_template, request, render_template_string, redirect, current_app
from multiprocessing import Process
from ..main import db
from . import app
from . import phantom
from .models import Xss2
flag1 = 'lectureCTF{you-missed-the-deadline-but-good-job-anyway}'


@app.route('/de3110dce011088cd4add1950a49182f')
def xss_set_flag_cookie():
    redirect_to_index = redirect('/')
    response = current_app.make_response(redirect_to_index)
    response.set_cookie('totally_not_the_flag', value=flag1)
    return response


@app.route('/<xss_id>')
def xss_post_page(xss_id):
    if xss_id == '404':
        return render_template_string('')

    xss = Xss2.query.filter_by(id=xss_id).scalar()
    if xss is None:
        return render_template_string("404")
    print('[+] XSS Payload Request: ID: ', xss_id, xss.content, '|', xss.id,
          '|', xss.title)
    return render_template('n_post.html', xss=xss)


@app.route('/', methods=['GET', 'POST'])
@app.route('/create', methods=['GET', 'POST'])
def xss_create_page():
    if request.method == 'GET':
        message = 'hello'
        return render_template('n_create.html', message=message)
    elif request.method == 'POST':
        title = request.form.get('title', '')
        content = request.form.get('content', '')
        # process payload here if you want to do anything with it
        title = xss_filter(title)
        content = xss_filter(content)
        new_xss = Xss2(title=title, content=content)
        db.session.add(new_xss)
        db.session.commit()
        if "PhantomJS" not in request.headers['User-Agent']:
            print("Calling phantomJS")
            p = Process(
                target=phantom.xss_get,
                args=(request.url_root + str(new_xss.id), ))
            p.start()
        return render_template(
            'n_success.html', id=new_xss.id, title=title, content=content)


def xss_filter(payload):
    payload = payload.replace(" ", "")
    payload = payload.replace(".", "")
    return payload

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">lectureCTF</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"> <a class="nav-link" href="{{url_for('demo.reflect')}}">reflect</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{{url_for('demo.badreflect')}}">badreflect</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{{url_for('demo.domxss1')}}">domxss1</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{{url_for('demo.otherheaders')}}">otherheaders</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{{url_for('demo.demoangular')}}">demoangular</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{{url_for('normal_xss.xss_create_page')}}">level1</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{{url_for('base_xss.xss_create_page')}}">level2</a> </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" style="padding-top: 2em;">
      <div class="row">
        <div class="col">
        {% block content %}
        {% endblock content %}
        </div>
      </div>
    </div>

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>